### ISSUE TITLE
не работает переключение после lock

### ISSUE THREAD

**Issue by AlexTransit** [BladeMight/Mahou#184]
давно заметил что переключение иногда как то странно себя ведет. но не знал как эмулировать "странности"
теперь знаю как. :) 
если "заблокировать" винду, (в ручную или по там ауту) то после разблокировки, звук переключения есть, а переключения нет. (конвертация последнего слова. вручную)
если сделать конвертацию выделенного текста, то часть слова меняет раскладку а часть нет.
если конвертировать несколько раз одно и тоже, то начинаются проблемы. ( проц загружает, и в таск баре циклично постоянно меняет раскладку)
не зависит от кого (юзера или админа) запущена программа.
лечиться только перезапуском проги.
после рестарта вроде все стабильно.

возможно дело в запущенной проге от logitech (setpoint), которая управляет кастомными кнопками клавы и мыши.

**Comment by BladeMight** [comment]
При блокировке винды вернее всего при нажатии Win+L, или при 
удерживании какого-то модификатора, который в последствии в Mahou считается 
все-еще-нажатым после разблокировки, т.к. Mahou словил нажатие Win но отпуск - 
нет, т.к. после нее нажалась L которая вызывает блокировку. Можно решить 
проблему понажимав на все(ну или конкретно какие-то если знать 
какие) модификаторы и левые и правые и тогда все заработает.
 
По поводу выделенного: если используете релиз версию(не latest-commit) 
попробуйте в latest-commit, обновившись через вкладку Обновления с каналом 
обновлений на latest-commit.
Еще если неправильно работает попробуйте выключить(если включена) функция 
смены раскладки в выделенном во вкладке Функции и включить функцию "Считать 
раскладку для всего слова". А еще если включена функция постоянной/единой 
раскладки попробуйте без них. Еще попробуйте с эмуляцией переключения 
раскладки и без. И еще последнее попробуйте с/без функции "Получать 
раскладку с JKL". 
 
Не думаю что дело в другой проге, т.к. мне уже писали о подобных 
проблемах.



- BladeMight
28.06.2018 12:58 Alexey Milko (notifications@github.com) 

  давно заметил что переключение иногда как то странно себя ведет. но не знал 
  как эмулировать "странности"теперь знаю как. :)если "заблокировать" 
  винду, (в ручную или по там ауту) то после разблокировки, звук переключения 
  есть, а переключения нет. (конвертация последнего слова. вручную)если 
  сделать конвертацию выделенного текста, то часть слова меняет раскладку а 
  часть нет.если конвертировать несколько раз одно и тоже, то начинаются 
  проблемы. ( проц загружает, и в таск баре циклично постоянно меняет 
  раскладку)не зависит от кого (юзера или админа) запущена 
  программа.лечиться только перезапуском проги.после рестарта вроде все 
  стабильно.
  возможно дело в запущенной проге от logitech (setpoint), которая управляет 
  кастомными кнопками клавы и мыши.
  —You 
  are receiving this because you are subscribed to this thread.Reply to this 
  email directly, view 
  it on GitHub, or mute 
  the thread.
  {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/BladeMight/Mahou","title":"BladeMight/Mahou","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/BladeMight/Mahou"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"не работает переключение после lock (#184)"}],"action":{"name":"View Issue","url":"https://github.com/BladeMight/Mahou/issues/184"}}}

  [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/BladeMight/Mahou/issues/184",
"url": "https://github.com/BladeMight/Mahou/issues/184",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "не работает переключение после lock (#184)",
"sections": [
{
"text": "",
"activityTitle": "**Alexey Milko**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@AlexTransit",
"facts": [
{
"name": "Repository: ",
"value": "BladeMight/Mahou"
},
{
"name": "Issue #: ",
"value": 184
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"BladeMight/Mahou\",\n\"issueId\": 184,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"BladeMight/Mahou\",\n\"issueId\": 184\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/BladeMight/Mahou/issues/184"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 351035864\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by AlexTransit** [comment]
Ok. поставил latest
блокирую всегда только "по старинке" ctrl+alt+delete enter (до сих пор не могу привыкнуть к винкею)

стояло "смена раскладки в Конверт выделения 
и она же +
сейчас, в dev версии, отображается красным цветом. (выключил)
и стоит получение раскладки с JKL 

с каками флагами "поиграться" я понял.
попробую разные варианты.

**Comment by AlexTransit** [comment]
немного поэксперементировал. с настройками и зависимостями.
win10. юзер с правами юзера 
переключение раскладки "break"
переключение выделенного текста "shift+break"
![image](https://user-images.githubusercontent.com/15162113/42144768-60565d3a-7dd6-11e8-89d7-a35ce41e8e03.png)

если блокировать экран (ctrl+del enter)
то после разблокировки 100% не переключает по break. звук переключения есть, а переключения нет. лечиться пезапуском.

смена раскладки выделенного текста, (после unlock)
пишем "tckb " нажимаем break. (ничего не происходит)
нажимаем "home shift+end shift+break" и получам "залипание"

**Comment by BladeMight** [comment]
@AlexTransit

> лечиться пезапуском

 Ну тут все понятно. Как я и говорил раньше: 

> т.к. Mahou словил нажатие Win но отпуск

Только в данном случае не <kbd>Win</kbd> а <kbd>Ctrl</kbd> и <kbd>Alt</kbd>... Т.е. если их нажать и отпустить после разблокировки то переключение заработает. 

Ну а проблема происходит из-за того что у *окна* "Ctrl+Alt+DELETE" и *окна* "Блокировки" есть больше прав чем у Mahou(или других программ от администратора)т.к. эти *окна* являются более *системными* чем *пользовательскими*, т.е. в итоге нажатия клавиш в этих *окнах* не ловятся ничем, проверял в AHK:
```ahk
#persistent
#installKeybdHook
keyHistory
```
После Ctrl+Alt+Delete отпуска клавиш и блокировки, в логе не пишется что я их отпускал, т.е. хуки клавиатур в этих *окнах* не работают.

**Comment by AlexTransit** [comment]
спасибо за разъяснения. а можно как то с командной строки Mahou перезапустить?

**Comment by BladeMight** [comment]
Пока команды из командной строки еще не добавлял, можно добавить.

**Comment by BladeMight** [comment]
> я бы в таск на unlock это прописал бы. :)

Нашел еще решение: Словить **нажатие**(не отпуск) `Delete` **можно** а значит если Ctrl+Alt+Delete то сбросить модификаторы в коде Mahou, добавил в latest-commit, можно проверять:
А еще по поводу ключей командой строки тоже готово, можно пробовать в latest-commit, ключи `-R`, `/R` или `R`(не зависимо от регистра):

`W:\here\Mahou\Mahou.exe /R`

**Comment by AlexTransit** [comment]
походу проблема ушла. (сбрасывание модификаторов)
за несколько дней незаметил ни одного глюка. 
так же ушла проблема с конвертацией выделенного текста.
получается что надобность в перезапуске через CLI отпадает.

**Comment by AlexTransit** [comment]
за неделю не было ни одной проблемы связанной с lock/unlock
можно вносить в релиз.

**Comment by BladeMight** [comment]
Готово [Mahou-v2.7.3.1](https://github.com/BladeMight/Mahou/releases/tag/v2.7.3.1)
