### ISSUE TITLE
MachineLearning/Anomalous.95% found with Malwarebytes in jklx86.exe

### ISSUE THREAD

**Issue by ViRGiL175** [BladeMight/Mahou#186]
## Problem/Request description

Hi. 

Installed Malwarebytes today. And Mahou updating interrupted with this warning:
![image](https://user-images.githubusercontent.com/11541555/42687507-10bba3e8-86aa-11e8-941f-118b6d58cde8.png)

Found strange `MachineLearning/Anomalous` thing in `jklx86.exe` file. Quarantined.

What is this? False alarm? Bad dependencies? Hidden mining?
I'm scared. 

## Expected behavior (Only if reporting bug)

Expecting clean and topnotch open source software.

## System information

- Windows version: Windows 10
- Windows architecture: x64
- .Net version: Last version, I guess. I'm updating everything
- Mahou version: 2.7.3.1

**Comment by BladeMight** [comment]
@ViRGiL175  

> What is this? False alarm? Bad dependencies? Hidden mining?
I'm scared.

No worry, thats a false alarm, I would **never** do such a thing. If you'd like you can see what actually jklx86.exe is doing by looking into its source: https://github.com/BladeMight/Mahou/blob/master/JKL/jklx86.c, if you don't understand the code then in other words:
`jkl` and `jklx86` are companions to the Mahou, they allow Mahou to detect whenever keyboard layout changes, and send a message to Mahou.

> MachineLearning/Anomalous

Maybe that is because it monitors keyboard layout changes. E.g. `WH_CALLWNDPROC` hook. 

> open source software

It is open source after all :)

You can use Mahou without it, but then correct layout detection will not work in some apps like CMD.exe(console apps). Just disable the JKL feature in Functions tab. 
Or you can add it in yours excluded list.

**Comment by ViRGiL175** [comment]
Oh, yeah. After some last updates I noticed that Mahou begun working in my Git Bash (or in my IDEA terminal, don't remember exactly).

Also now my friends told me that BattleEye anti-cheat software for PUBG game also blocked `jkl` loading by some mysterious reasons. This seemed suspicious and they not using the program now.

I'm happy and calm with your fast explanations, thank you. There is no problem. Should I close my Issues myself?

But maybe some old/deprecated/dangerous Win API or somethingt else is used there? It's sad to scare off users from excellent software due to false alarms.

**Comment by BladeMight** [comment]
> But maybe some old/deprecated/dangerous Win API or somethingt else is used there?

There **only** one WinAPI way to monitor keyboard layout switching and it is "WH_CALLWNDPROC" hook. 

Maybe signing the executables will help, but i don't have any certificate, and they're not free. Also maybe that is because its in C/C++, so these Anti-(Malicious/Virus) softwares seek the binary code for these \*dangerous\*(but useful) WinAPI functions, and in C# executables "WH_CALLWNDPROC" hook is not possible, so thats how things are...

> Should I close my Issues myself?

That would be great.

**Comment by ViRGiL175** [comment]
> they're not free

Are [LetsEncrypt](https://letsencrypt.org/) certificates not suitable for signing Microsoft applications?

It's free and (relatively) easy to obtain. It is not "premium" "named" certificate, but web-wide trusted and working like charm.

**Comment by BladeMight** [comment]
I think *maybe it would* be possible, but i also don't have `signtool.exe`(wonder if there any other tool...) to sign executables, due to not using Visual Studio.

**Comment by ViRGiL175** [comment]
So anyway, thanks for great Mahou! You saved a lot of my nerves and time in wrong-layout-situations.

Hope there will be solution for false warnings.
