### ISSUE TITLE
Как cделать замену транслитерации на "ничего"(проблема транслитерации)?

### ISSUE THREAD

**Issue by yuklov** [BladeMight/Mahou#256]
Здравствуйте!

Хочу в транслитерации букву "ь" перевести ничем. Например:

альфа = alfa
Игорь = Igor
словарь = slovar

Добавил в TSDict.txt правилу "ь|", но тогда функция транслитерации перестала работать.

Помогите, пожалуйста.

**Comment by BladeMight** [comment]
Привет,
 
Хм, я про "ничего" не думал, ок сейчас добавлю, подожди...



- BladeMight
16.01.2020 10:31 yuklov (notifications@github.com) 

  Здравствуйте!
  Хочу в транслитерации букву "ь" перевести ничем. Например:
  альфа = alfaИгорь = Igorсловарь = slovar
  Добавил в TSDict.txt правилу "ь|", но тогда функция транслитерации 
  перестала работать.
  Помогите, пожалуйста.
  —You 
  are receiving this because you are subscribed to this thread.Reply to this 
  email directly, view 
  it on GitHub, or unsubscribe.
  [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/BladeMight/Mahou/issues/256?email_source=notifications\u0026email_token=AC3BB4BFQPBKVLMI4K5U7QLQ6ALPLA5CNFSM4KHQAVI2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IGSJGDA",
"url": "https://github.com/BladeMight/Mahou/issues/256?email_source=notifications\u0026email_token=AC3BB4BFQPBKVLMI4K5U7QLQ6ALPLA5CNFSM4KHQAVI2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IGSJGDA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by BladeMight** [comment]
https://github.com/BladeMight/Mahou/issues/257#issuecomment-575053246
