### ISSUE TITLE
Предложение: поддержка форматирования в буфере обмена

### ISSUE THREAD

**Issue by yuklov** [BladeMight/Mahou#257]
Я сегодня начал использовать Mahou. Мне очень нравился. Даже лучше чем известные переключатели.

Предложение
Сейчас при конвертирования и транслитерации формат текста исчезает. Если бы сохранился, было бы здорово. 

![изображение](https://user-images.githubusercontent.com/59954194/72507803-6923e080-3866-11ea-9673-d08ce965d454.png)

**Comment by BladeMight** [comment]
Добавил возможность в транслитерации заменять на "ничего":
 
ь|
 
или
 
|ь
 
в Mahou latest-commit. <fe48e46>
 
Ну насчёт формата, имеешь в виду "жирный" и т.д. стили текста? Если 
да, то не получится, Mahou *берёт* текст как *текст*
 
(можно конечно подумать над сохранением формата, но нужно будет разобратся 
в каком формате хранится в буфере обмена, мне казалось что может в https://ru.wikipedia.org/wiki/Rich_Text_Format, может 
оно так и есть, но я не смогу этого определить обычными WinAPI, т.к. у 
них в стандартных форматах нет такого: https://docs.microsoft.com/en-us/windows/win32/dataxchg/standard-clipboard-formats, 
придется придумывать определитель для каждого формата...)
 
, поэтому возвращает тоже текст. Можно как вариант использовать 
markdown, там явно указывается стиль символами.
Для обновления до latest-commit:
1. Во вкладке "Обновления" поставить канал обновлений на 
LatestCommit(Beta), и обновиться как обычно(проверить, скачать обновление)
2. На странице: https://github.com/BladeMight/Mahou/releases/tag/latest-commit 
есть постоянно авто-обновляемые сборки. (если не знаешь какую брать - 
Release_x86_x64.zip)



- BladeMight
16.01.2020 10:47 yuklov (notifications@github.com) 

  Я сегодня начал использовать Mahou. Мне очень нравился. Даже лучше чем 
  известные переключатели.
  ПредложениеСейчас при конвертирования и транслитерации формат текста 
  исчезает. Если бы сохранился, было бы здорово.
  
  —You 
  are receiving this because you are subscribed to this thread.Reply to this 
  email directly, view 
  it on GitHub, or unsubscribe.
  [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/BladeMight/Mahou/issues/257?email_source=notifications\u0026email_token=AC3BB4GB43O7TUK4XCH3DVLQ6ANJTA5CNFSM4KHQGK2KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IGSMSZQ",
"url": "https://github.com/BladeMight/Mahou/issues/257?email_source=notifications\u0026email_token=AC3BB4GB43O7TUK4XCH3DVLQ6ANJTA5CNFSM4KHQGK2KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IGSMSZQ",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by yuklov** [comment]
> 
> Добавил возможность в транслитерации заменять на "ничего":   ь|   или   |ь   в Mahou latest-commit. <fe48e46>   Ну насчёт формата, имеешь в виду "жирный" и т.д. стили текста? Если да, то не получится, Mahou *берёт* текст как *текст*   (можно конечно подумать над сохранением формата, но нужно будет разобратся в каком формате хранится в буфере обмена, мне казалось что может в https://ru.wikipedia.org/wiki/Rich_Text_Format, может оно так и есть, но я не смогу этого определить обычными WinAPI, т.к. у них в стандартных форматах нет такого: https://docs.microsoft.com/en-us/windows/win32/dataxchg/standard-clipboard-formats, придется придумывать определитель для каждого формата...)   , поэтому возвращает тоже текст. Можно как вариант использовать markdown, там явно указывается стиль символами. Для обновления до latest-commit: 1. Во вкладке "Обновления" поставить канал обновлений на LatestCommit(Beta), и обновиться как обычно(проверить, скачать обновление) 2. На странице: https://github.com/BladeMight/Mahou/releases/tag/latest-commit есть постоянно авто-обновляемые сборки. (если не знаешь какую брать - Release_x86_x64.zip) - BladeMight 16.01.2020 10:47 yuklov (notifications@github.com) Я сегодня начал использовать Mahou. Мне очень нравился. Даже лучше чем известные переключатели. ПредложениеСейчас при конвертирования и транслитерации формат текста исчезает. Если бы сохранился, было бы здорово. —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "#257?email_source=notifications\u0026email_token=AC3BB4GB43O7TUK4XCH3DVLQ6ANJTA5CNFSM4KHQGK2KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IGSMSZQ", "url": "#257?email_source=notifications\u0026email_token=AC3BB4GB43O7TUK4XCH3DVLQ6ANJTA5CNFSM4KHQGK2KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IGSMSZQ", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]


Спасибо большое!!!
Форматирование не очень важно.

**Comment by BladeMight** [comment]
Рад что тебе нравится Mahou.
 
Удачи.
P.S. (лучше всегда использовать latest-commit)
 



- BladeMight
16.01.2020 11:12 yuklov (notifications@github.com) 

  
    Добавил возможность в транслитерации заменять на "ничего": ь| или |ь в 
    Mahou latest-commit. Ну насчёт формата, имеешь в виду "жирный" и т.д. стили 
    текста? Если да, то не получится, Mahou берёт текст как 
    текст (можно конечно подумать над сохранением формата, но нужно 
    будет разобратся в каком формате хранится в буфере обмена, мне казалось что 
    может в https://ru.wikipedia.org/wiki/Rich_Text_Format, может оно 
    так и есть, но я не смогу этого определить обычными WinAPI, т.к. у них в 
    стандартных форматах нет такого: https://docs.microsoft.com/en-us/windows/win32/dataxchg/standard-clipboard-formats, 
    придется придумывать определитель для каждого формата...) , поэтому 
    возвращает тоже текст. Можно как вариант использовать markdown, там явно 
    указывается стиль символами. Для обновления до latest-commit: 1. Во вкладке 
    "Обновления" поставить канал обновлений на LatestCommit(Beta), и обновиться 
    как обычно(проверить, скачать обновление) 2. На странице: https://github.com/BladeMight/Mahou/releases/tag/latest-commit 
    есть постоянно авто-обновляемые сборки. (если не знаешь какую брать - 
    Release_x86_x64.zip) - BladeMight 16.01.2020 10:47 yuklov (notifications@github.com) Я 
    сегодня начал использовать Mahou. Мне очень нравился. Даже лучше чем 
    известные переключатели. ПредложениеСейчас при конвертирования и 
    транслитерации формат текста исчезает. Если бы сохранился, было бы здорово. 
    —You are receiving this because you are subscribed to this thread.Reply to 
    this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { 
    "@type": "ViewAction", "target": "#257?email_source=notifications\u0026email_token=AC3BB4GB43O7TUK4XCH3DVLQ6ANJTA5CNFSM4KHQGK2KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IGSMSZQ", 
    "url": "#257?email_source=notifications\u0026email_token=AC3BB4GB43O7TUK4XCH3DVLQ6ANJTA5CNFSM4KHQGK2KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IGSMSZQ", 
    "name": "View Issue" }, "description": "View this Issue on GitHub", 
    "publisher": { "@type": "Organization", "name": "GitHub", 
    "url": "https://github.com" } } ]
  Спасибо большое!!!Форматирование не очень важно.
  —You 
  are receiving this because you commented.Reply to this email directly, view 
  it on GitHub, or unsubscribe.
  [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/BladeMight/Mahou/issues/257?email_source=notifications\u0026email_token=AC3BB4DUMEQY6QA3UXE5Y7LQ6AQIRA5CNFSM4KHQGK2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJDKQZI#issuecomment-575055973",
"url": "https://github.com/BladeMight/Mahou/issues/257?email_source=notifications\u0026email_token=AC3BB4DUMEQY6QA3UXE5Y7LQ6AQIRA5CNFSM4KHQGK2KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJDKQZI#issuecomment-575055973",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
