### ISSUE TITLE
Can't replace three dots to «…» (Alt+0133) with snippets.

### ISSUE THREAD

**Issue by vort3** [BladeMight/Mahou#268]
## Problem

Can't replace three dots with a … symbol (Alt+0133) with snippets; here's what I use:
```
->regex/^\.{3}$/i
====>… <====
```

I tried to play around with regex, but couldn't make it work anyway.

## Expected behavior

Test... -> Test… 

## System information

- Windows version: Windows 10 LTSC
- Windows architecture: x64
- .Net version: v4.0.30319.42000
- Mahou version: Mahou 2.9.0.1-dev <d41372c>

## Log
Here I am trying to replace "test..." to "test…", but it doesn't work. Simply typing "..." (without any previous word) works fine.
https://hastebin.com/seqamawazo.sql

**Comment by BladeMight** [comment]
When you writing three dots you write a word before it, that not only three dots, that is a word and three dots, since that is the problem the regex should be as such:

```
->regex/^(.+)\.{3}$/i
====>$1… <====
```

and since Mahou have "two words" matching feature, you should avoid two word matching for this rule;
```
->regex/^([^ ]+)\.{3}$/i
====>$1… <====
```
E.g. don't match if it contains space. The "two word matching" is useful when two words should become one, for example:
```
->regex/(seventy)\s(three)/i
====>$1-$2 <====
```

You should avoid matching the two words whenever that is not needed, this can be done by:
1. changing the `.*`/`.+` to `[^ ]*`/`[^ ]+`
2. adding at the end: `(?!.* )`
3. or something like that that excludes space from match.

when space is present is two-word match, when not - one word.

**Comment by vort3** [comment]
Thanks, it works, Issue can be closed!

> changing the `.*`/`.+` to `[^ ]*`/`[^ ]+`

Yeah I was trying to use something like `.*\.{3}`, but for some reason this doesn't work, I don't know why `[^ ]` works better, but anyway, I can finally use it as I want.

**Comment by BladeMight** [comment]
> , I don't know why `[^ ]` works better

Because of `two word matching` in Mahou snippets.

First Mahou checks currently inputted word after you press space as snippet, and stores it in "second word".
When you enter another word with space Mahou also checks it, and then checks combined word1+word2(or better to say last_word+current_word), so avoiding the match for space makes it not match two-word checks.
