### ISSUE TITLE
Greek flag

### ISSUE THREAD

**Issue by acicovic** [BladeMight/Mahou#291]
Hello there,

I have started using Mahou, mainly for the flag indication next to the mouse cursor. However, it doesn't have a flag for Greek, which is a language that I use.

Could it be added in the next release? Do you need any help?

Thanks.

**Comment by BladeMight** [comment]
Hello,
Can you tell me your layout code? Visible in Layouts tab, when selecting 
inside ListBoxes: example: LayoutName(9999) where 9999 should be 
code.



- BladeMight
07.10.2020 20:50 Alex Cicovic (notifications@github.com) 

  
  Hello there,
  I have started using Mahou, mainly for the flag indication next to the 
  mouse cursor. However, it doesn't have a flag for Greek, which is a language 
  that I use.
  Could it be added in the next release? Do you need any help?
  Thanks.
  —You 
  are receiving this because you are subscribed to this thread.Reply to this 
  email directly, view 
  it on GitHub, or unsubscribe.
  [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/BladeMight/Mahou/issues/291",
"url": "https://github.com/BladeMight/Mahou/issues/291",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by BladeMight** [comment]
@acicovic Does that flag seems fine(draw it myself)
![ru](https://user-images.githubusercontent.com/11931888/95369388-0ab0fd80-08e0-11eb-9845-06b130da4fbb.png)

Is your layout code `67634184` ?

**Comment by BladeMight** [comment]
Or choose from one of these, I am unsure which one looks better...:
1.![1](https://user-images.githubusercontent.com/11931888/95371054-59f82d80-08e2-11eb-8150-99ca4989ad17.png) (Top and bottom with white lines)
2.![2](https://user-images.githubusercontent.com/11931888/95371074-611f3b80-08e2-11eb-9aa6-aad74f7113f5.png) (Stretched "cross")
3.![3](https://user-images.githubusercontent.com/11931888/95371090-64b2c280-08e2-11eb-861c-f84542b63379.png) (Double borders around top and bottom)
4.![4](https://user-images.githubusercontent.com/11931888/95371135-74320b80-08e2-11eb-9ed6-dd758d3ed2ad.png) (This one looks better but its 2px smaller in height than other flags in Mahou...  and it will be noticeable when switching layouts)

**Comment by acicovic** [comment]
Hi,

Layout code is indeed 67634184. I'll look at the pics and tell you.

**Comment by acicovic** [comment]
Hi @BladeMight 

Go with number 1 or with the one I'm attaching your here. I added an extra white and blue stripe at the bottom. I think it looks just a bit better, but it isn't a 100% accurate depiction of the flag. So if you want a 100% accurate depiction go with 1. Also, take a look yourself to see which you prefer.

![5](https://user-images.githubusercontent.com/23142906/95374481-105e1180-08e7-11eb-8429-6cd27d77bf0a.png)

Thanks! 👍

**Comment by BladeMight** [comment]
Added Your Flag(looks better to me) in 516f078, update to latest-commit version:

1. Through Mahou => Set Updates Channel to `LatestCommit(Beta)` and Press `Check for updates`, then download.

or 

2. Download manually `Release_x86_x64.zip` from [here](https://github.com/BladeMight/Mahou/releases/tag/latest-commit)

**Comment by acicovic** [comment]
Work very well, thanks 👍
